### ISSUE TITLE
Backend 

### ISSUE THREAD

**Issue by Fo4Ik-git** [jagaOff/ChatForGods#10]
- [X] Сделать Websocket Exception Handler с выводом ошибок
- [X] User <JWT> токен для проверки авторизации и тд
- [ ] Password Encoder

**Comment by Zephir0g** [comment]
Websocket Exception Handler done
![image](https://github.com/jagaOff/ChatForGods/assets/98671266/04e8c15e-6cf3-4e0d-b501-f9ad4aef456f)

**Comment by Zephir0g** [comment]
Токен сделан круто и классно!
